spring.application.name=driver-service-java


server.port=8080

# ------------------------------------------------------------------------------
# KAFKA PRODUCER CONFIGURATION
# ------------------------------------------------------------------------------
# 1. Tell Spring where the Kafka broker is running on your host machine
spring.kafka.producer.bootstrap-servers=localhost:9092

# 2. Define how keys and values should be serialized into bytes before transmission.
# Since we are working with JSON, treating them as raw Strings is the most flexible approach.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
